[package]
edition = "2021"
name = "voting_client"
version = "0.1.0"

[lib]
path = "mod.rs"

[features]
anchor = []
anchor-idl-build = []
default = []
fetch = []
serde = ["dep:serde", "dep:serde_with"]

[dependencies]
# 核心依赖
borsh = "1.5.1"
solana-account-info = "2.3.0"
solana-cpi = "2.2.1"
solana-decode-error = "2.3.0"
solana-instruction = "2.3.0"
solana-msg = "2.2.1"
solana-program = "2.3.0"
solana-program-entrypoint = "2.3.0"
solana-program-error = "2.2.2"
solana-pubkey = "2.3.0"

# 其他必要的辅助库
num-derive = "0.4"
num-traits = "0.2"
thiserror = "2.0.12"

# serde 依赖，设为可选
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_with = { version = "3.8", optional = true, features = ["macros"] }
