# .github/workflows/ci.yml

name: Anchor CI & Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境 (使用官方 Action)
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22" # 使用 "22" 来获取最新的 v22 版本

      # 3. 设置 PNPM (安装 pnpm 本身)
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: "10.8.1"

      # 4. 验证 Node.js 版本
      - name: Verify Node.js Version
        run: node -v

      # 5. 安装客户端依赖
      - name: Install JS dependencies
        run: pnpm install --frozen-lockfile

      # 6. 运行 Anchor 构建和测试
      #    使用一体化 action，并传入您指定的最新版本号
      - name: Build and Run Anchor Tests
        uses: metadaoproject/anchor-test@v2.2
        with:
          anchor-version: "0.32.1"
          solana-cli-version: "2.3.13"
          node-version: "22"

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build_and_test
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --latest --strip header
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          body: ${{ steps.git-cliff.outputs.content }}
          prerelease: contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc')
